# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 0, 300, 100))
        self.plainTextEdit.setStyleSheet("QtPlainText{\n"
"boredr: 2px solid #A4D04D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(0, 120, 300, 30))
        self.lineEdit.setStyleSheet("QtLineEdit{\n"
"border: 2px solid #A4004D;\n"
"background-color:#404040;\n"
"color:white;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 160, 260, 40))
        self.pushButton.setStyleSheet("QtPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color:#404040;\n"
"color:white;\n"
"}\n"
"\n"
"QtPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color:#444444;\n"
"color:white;\n"
"}\n"
"\n"
"QtPushButton:pressed{\n"
"border: 2px solid white;\n"
"background-color:#444444;\n"
"color:white;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 220, 260, 40))
        self.pushButton_2.setStyleSheet("QtPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color:#404040;\n"
"color:white;\n"
"}\n"
"\n"
"QtPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color:#444444;\n"
"color:white;\n"
"}\n"
"\n"
"QtPushButton:pressed{\n"
"border: 2px solid white;\n"
"background-color:#444444;\n"
"color:white;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Скачать видео"))
        self.pushButton_2.setText(_translate("MainWindow", "->    /.."))
